'use client';
import { useState, useMemo, useRef, useEffect } from 'react';
import { Bank, UsersThree, Books, CheckSquare, ArrowUpRight, ArrowRight, MagnifyingGlass, X, ArrowLeft, DownloadSimple, Info, Envelope, SquaresFour } from '@phosphor-icons/react';
import Foto from './Foto';
import FichaDiputado from './FichaDiputado';
import TarjetaDiputado from './TarjetaDiputado';
const normalize=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const value=v=>typeof v==='object'?v?.$value||'No informado':v||'No informado';
const date=s=>s?new Intl.DateTimeFormat('es-CL',{dateStyle:'medium',timeZone:'America/Santiago'}).format(new Date(s)):'No informada';
const tabs=[['diputados','Representantes',UsersThree],['comisiones','Comisiones',SquaresFour],['proyectos','Proyectos de ley',Books],['votaciones','Votaciones',CheckSquare]];
async function lookup(kind,id){const r=await fetch('/api/congreso?'+new URLSearchParams({kind,id}));const j=await r.json();if(!r.ok)throw new Error(j.error);return j.data;}
function Empty({title,children}){return <div className="empty"><MagnifyingGlass size={32}/><h3>{title}</h3><p>{children}</p></div>;}
function LegislativeSearch({kind}){
  const [id,setId]=useState(''),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[searched,setSearched]=useState(false),[detail,setDetail]=useState(null),[detailBusy,setDetailBusy]=useState(null);
  async function submit(e){e.preventDefault();setBusy(true);setError('');setResult(null);setDetail(null);setSearched(false);try{setResult(await lookup(kind==='proyectos'?'project':'votes',id.trim()));setSearched(true);}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function openVote(id){setDetailBusy(id);setError('');setDetail(null);try{setDetail(await lookup('vote',String(id)));}catch(e){setError(e.message);}finally{setDetailBusy(null);}}
  return <><form className="legislative-form" onSubmit={submit}><label htmlFor="boletin">Número de boletín</label><div className="search-line"><input id="boletin" value={id} onChange={e=>setId(e.target.value)} required pattern="[0-9]{1,6}(-[0-9]{2})?" placeholder="Ej. 8575-05"/><button className="primary" disabled={busy}>{busy?'Consultando…':'Consultar'}<ArrowRight size={18}/></button></div><p className="caption">{kind==='proyectos'?'Ingresa el correlativo o el boletín completo para consultar la tramitación en el Senado.':'Usa el boletín completo, incluida la materia (por ejemplo, 8575-05). Resultados de la Cámara de Diputadas y Diputados.'}</p></form>
  <div aria-live="polite">{error&&<p className="notice" role="alert">{error}</p>}{busy&&<div className="skeleton"/>}
  {!busy&&!searched&&!error&&<Empty title={kind==='proyectos'?'Sigue el recorrido de una ley':'Conoce cómo se votó'}>Consulta un boletín para explorar {kind==='proyectos'?'su estado y sus últimas actuaciones.':'los resultados y el detalle de cada votación.'}</Empty>}
  {searched&&(!result||(Array.isArray(result)&&!result.length))&&<Empty title="Sin registros para este boletín">Revisa el número. La ausencia de registros en este servicio no implica que el proyecto no exista.</Empty>}
  {kind==='proyectos'&&result&&<article className="project-result"><span className="badge">Boletín {result.boletin}</span><h2>{result.titulo}</h2><div className="project-meta"><div><small>Estado</small><strong>{result.estado||'No informado'}</strong></div><div><small>Ingreso</small><strong>{result.fecha_ingreso||'No informado'}</strong></div><div><small>Iniciativa</small><strong>{result.iniciativa||'No informada'}</strong></div></div><p>{result.etapa} · {result.urgencia_actual}</p><a className="text-link" href={result.source} target="_blank" rel="noreferrer">Ver registro original <ArrowUpRight/></a><h3>Tramitación</h3><div className="timeline">{result.tramites.map((t,i)=><div key={i}><time>{t.FECHA}</time><p>{t.DESCRIPCIONTRAMITE}<small>{t.CAMARATRAMITE} · {t.ETAPDESCRIPCION}</small></p></div>)}</div></article>}
  {kind==='votaciones'&&Array.isArray(result)&&result.map(v=><article className="vote" key={v.ID}><div><span className="caption">{date(v.Fecha)} · Votación {v.ID}</span><h3>{value(v.Resultado)}</h3><p>{v.Articulo||value(v.Tipo)}</p></div><div className="vote-counts"><span><b>{v.TotalAfirmativos}</b>A favor</span><span><b>{v.TotalNegativos}</b>En contra</span><span><b>{v.TotalAbstenciones}</b>Abstenciones</span></div><button className="secondary" disabled={detailBusy!==null} onClick={()=>openVote(v.ID)}>{detailBusy===v.ID?'Consultando…':'Ver votos'}<ArrowRight size={16}/></button>{detail?.ID===v.ID&&<div className="vote-detail"><h4>Voto individual</h4>{detail.votos.length?detail.votos.map((d,i)=><div key={i}><span>{d.nombre}</span><strong>{d.opcion}</strong></div>):<p>La fuente no entregó el detalle individual.</p>}</div>}</article>)}</div></>;
}
export default function Explorer({data}){
  const [tab,setTab]=useState('diputados'),[search,setSearch]=useState(''),[party,setParty]=useState(''),[page,setPage]=useState(1),[person,setPerson]=useState(null);
  const [actividad,setActividad]=useState(null);
  useEffect(()=>{fetch('/api/congreso?kind=resumen').then(r=>r.ok?r.json():{}).then(j=>setActividad(j.data||{}),()=>setActividad({}));},[]);
  const parties=[...new Set(data.diputados.map(d=>d.partido))].sort();
  const filtered=useMemo(()=>data.diputados.filter(d=>normalize(d.nombreCompleto+' '+d.partido).includes(normalize(search))&&(!party||party===d.partido)),[data.diputados,search,party]);
  const pages=Math.max(1,Math.ceil(filtered.length/12));
  const visible=filtered.slice((page-1)*12,page*12);
  function go(id){setTab(id);setSearch('');setParty('');setPage(1);}
  function download(){const blob=new Blob([JSON.stringify(filtered,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='diputados-congreso.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return <div className="app-shell"><aside className="sidebar"><a className="brand" href="/"><Bank size={30} weight="fill"/><span>Diputados<small>CHILE · DATOS ABIERTOS</small></span></a><div className="side-label">EXPLORAR EL CONGRESO</div><nav aria-label="Secciones">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>go(id)} aria-current={tab===id?'page':undefined} className={tab===id?'active':''}><Icon size={21} weight={tab===id?'fill':'regular'}/>{label}{tab===id&&<ArrowRight size={16}/>}</button>)}</nav><div className="source-box"><Bank size={24}/><h3>Información pública.<br/>Más cerca de ti.</h3><p>Un espacio para entender a quienes te representan.</p><a href="https://opendata.congreso.cl" target="_blank" rel="noreferrer">Conocer la fuente <ArrowUpRight size={16}/></a></div><p className="side-footer">Explorador independiente<br/>Datos del Congreso Nacional</p></aside>
  <div className="workspace"><header className="topbar"><span>Congreso Nacional <span className="slash">/</span> <strong>Explorador legislativo</strong></span><a href="https://opendata.congreso.cl" target="_blank" rel="noreferrer">Datos abiertos <ArrowUpRight size={15}/></a></header>
  <main id="contenido"><section className="hero"><div className="eyebrow">LA DEMOCRACIA, A LA VISTA</div><h1>Conoce a quienes<br/><em>te representan.</em></h1><p>Explora las personas, las decisiones y el trabajo legislativo de Chile, desde su fuente pública.</p><div className="hero-actions"><button className="primary" onClick={()=>{go('diputados');document.getElementById('explorar').scrollIntoView({behavior:'smooth'});}}>Explorar representantes <ArrowRight size={18}/></button><a href="https://opendata.congreso.cl" target="_blank" rel="noreferrer" className="text-link">Sobre los datos <ArrowUpRight size={17}/></a></div><div className="editorial-mark" aria-hidden="true"><Bank weight="duotone"/><span>CONGRESO<br/>NACIONAL</span></div></section>
  <section className="stats" aria-label="Resumen de la consulta"><div><small>Representantes recibidos</small><strong>{data.errors.includes('diputados')?'—':data.diputados.length}</strong><span>Listado de la fuente</span></div><div><small>Comisiones recibidas</small><strong>{data.errors.includes('comisiones')?'—':data.comisiones.length}</strong><span>Registros disponibles</span></div><div className="stat-note"><Info size={22}/><p>La transparencia empieza<br/>por conocer la fuente.<small>Consulta realizada el {date(data.updatedAt)}.</small></p></div></section>
  <section id="explorar" className="explore"><div className="section-heading"><div><h2>{tabs.find(t=>t[0]===tab)[1]}</h2><p>{tab==='diputados'?'Encuentra un nombre y conoce su ficha parlamentaria.':tab==='comisiones'?'Espacios de trabajo legislativo informados por la Cámara.':tab==='proyectos'?'Del ingreso del proyecto a su publicación.':'Consulta los resultados y el voto individual por boletín.'}</p></div>{tab==='diputados'&&<button className="secondary" onClick={download} disabled={!filtered.length}><DownloadSimple size={17}/>Exportar</button>}</div>
  {(tab==='diputados'||tab==='comisiones')&&<p className="data-note"><Info size={16}/>El servicio puede entregar registros incompletos. Los campos ausentes se muestran como no informados; las cifras corresponden a esta consulta.</p>}
  {data.errors.includes(tab)&&<p className="notice" role="alert">No fue posible cargar {tab}. <button onClick={()=>window.location.reload()}>Reintentar</button></p>}
  {tab==='diputados'&&<><div className="filters"><label className="search-field"><span>Buscar representante</span><div><MagnifyingGlass size={20}/><input placeholder="Nombre o partido político" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></div></label><label><span>Partido político</span><select value={party} onChange={e=>{setParty(e.target.value);setPage(1);}}><option value="">Todos los partidos</option>{parties.map(p=><option key={p}>{p}</option>)}</select></label><button className="clear" onClick={()=>{setSearch('');setParty('');setPage(1);}}>Limpiar filtros</button></div><div className="results-label" aria-live="polite"><b>{filtered.length}</b> representantes <span>Ordenados por nombre</span></div>
  <div className="people-grid">{visible.map((d,i)=><TarjetaDiputado key={d.id} d={d} index={i} actividad={actividad?actividad[d.id]??null:undefined} onOpen={()=>setPerson(d)}/>)}</div>
  {!filtered.length&&<Empty title="No encontramos coincidencias">Prueba con un apellido o limpia los filtros.</Empty>}<div className="pagination"><span>{filtered.length?((page-1)*12+1)+'–'+Math.min(page*12,filtered.length):'0'} de {filtered.length} registros</span><div><button aria-label="Página anterior" disabled={page===1} onClick={()=>setPage(p=>p-1)}><ArrowLeft size={18}/></button><span>{page} / {pages}</span><button aria-label="Página siguiente" disabled={page===pages} onClick={()=>setPage(p=>p+1)}><ArrowRight size={18}/></button></div></div></>}
  {tab==='comisiones'&&data.comisiones.length>0&&data.comisiones.every(c=>!c.integrantes.length)&&<p className="notice" role="status">La Cámara aún no publica la composición de las comisiones del periodo actual. Esta sección se completará automáticamente cuando la fuente se actualice. <a className="text-link" href="https://opendata.camara.cl" target="_blank" rel="noreferrer">Ver fuente <ArrowUpRight size={14}/></a></p>}
  {tab==='comisiones'&&<div className="committee-grid">{data.comisiones.map(c=><article className="committee" key={c.id}><SquaresFour size={30} weight="duotone"/><span className="badge">{c.tipo}</span><h3>{c.nombre}</h3><p>Presidencia: {c.presidente||'No informada'}</p><details><summary>Integrantes</summary>{c.integrantes.length?c.integrantes.map((i,n)=><p key={n}>{i.nombre}</p>):<p>La fuente no informa integrantes en esta consulta.</p>}</details>{c.correo&&<a className="text-link" href={'mailto:'+c.correo}><Envelope size={17}/>{c.correo}</a>}</article>)}{!data.comisiones.length&&<Empty title="Sin comisiones disponibles">Vuelve a consultar más tarde.</Empty>}</div>}
  {(tab==='proyectos'||tab==='votaciones')&&<LegislativeSearch key={tab} kind={tab}/>}</section>
  <footer><span>Diputados · Explorador legislativo independiente</span><a href="https://opendata.congreso.cl" target="_blank" rel="noreferrer">Fuente y documentación <ArrowUpRight size={14}/></a></footer></main></div>{person&&<FichaDiputado person={person} committees={data.comisiones} onClose={()=>setPerson(null)}/>}</div>;
}
